language: node_js

os: osx

before_script:
  - npm install

script: 
  - npm test
  - npm run build


deploy:
  provider: pages
  local_dir: client/dist
  skip_cleanup: true
  github_token: $DEPLOYMENT_TOKEN
  keep_history: true
  on:
    branch: master  